services:
  # Backend Service
  - type: web
    name: inventory-backend
    env: docker
    plan: free
    region: singapore
    repo: https://github.com/nguyenthaitan/Inventory-Management
    branch: main

    # Render needs to know where the Dockerfile is relative to the REPO ROOT
    dockerfilePath: "02_Source/01_Source Code/infra/docker/backend.Dockerfile"

    # Render needs to know the build context (where '.' refers to in Dockerfile)
    dockerContext: "02_Source/01_Source Code/backend"

    # Environment variables
    envVars:
      - key: MONGO_URI
        sync: false # Must be provided in Render Dashboard
