version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/docker/backend.Dockerfile
    container_name: inventory_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - inventory_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/docker/frontend.Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    container_name: inventory_frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - inventory_network
    depends_on:
      - backend

networks:
  inventory_network:
    external: true
