mongo-url = "mongodb+srv://admin:123@inventorymanagement.kbyjdmp.mongodb.net/inventory_management_db?retryWrites=true&w=majority"
elasticsearch-urls = ["http://elasticsearch:9200"]

# 1. Quét lại toàn bộ dữ liệu cũ của 8 collections này khi khởi động
direct-read-namespaces = [
  "inventory_management_db.batch_components",
  "inventory_management_db.inventory_lots",
  "inventory_management_db.inventory_transactions",
  "inventory_management_db.label_templates",
  "inventory_management_db.materials",
  "inventory_management_db.production_batches",
  "inventory_management_db.qc_tests",
  "inventory_management_db.users"
]

# 2. Lắng nghe thay đổi Real-time của 8 collections này
change-stream-namespaces = [
  "inventory_management_db.batch_components",
  "inventory_management_db.inventory_lots",
  "inventory_management_db.inventory_transactions",
  "inventory_management_db.label_templates",
  "inventory_management_db.materials",
  "inventory_management_db.production_batches",
  "inventory_management_db.qc_tests",
  "inventory_management_db.users"
]

# 3. Các tùy chọn tối ưu
verbose = true